### ISSUE TITLE
Backend url

### ISSUE THREAD

**Issue by maciasb** [CPSCentral/dorm-web#105]
Come up with logic to toggle between localhost when in dev mode and public website when pushed out to TEST / MASTER

Morris will research whether or not environment variables are read-only and come up with a mechanism to toggle between localhost / prod API server... either via a link in the debug panel or as a NPM argument

**Comment by morriszcps** [comment]
Env vars are read only, cannot be changed at runtime. I modified the build logic so:
ng build - uses dev environment (localhost backend)
ng build --prod uses prod environment

npm start - builds using production environment
npm local - builds using dev environment
