### ISSUE TITLE
adjust price on device hover with full cart 

### ISSUE THREAD

**Issue by JackaCPS** [CPSCentral/dorm-web#116]
when there is already items in the customer's cart we need to adjust the prices on device hover to show the discounted price based on the cart.

**Comment by JackaCPS** [comment]
added styling, need new prices from api

**Comment by JackaCPS** [comment]
remove monitor category and add camera

**Comment by maciasb** [comment]
Passed necessary data from API and recreated the function to calculate discounts on Angular's side
